export interface Project {
  id: string;
  name: string;
  image: string;
  category: string[];
  description: string;
  tags: string[];
  live_link: string;
  github_link: string;
  company: string;
  logo: string;
  server_github_link: string;
  featured: boolean;
  tech_stack: string[];
  challenges: string[];
  achievements: string[];
  key_features: string[];
  role: string;
  duration: string;
  metrics: Record<string, string | number>;
}

export const projectCategories = [
  "All",
  "Full Stack",
  "Frontend",
  "Backend",
  "E-commerce",
  "Dashboard",
];

export const projectsData: Project[] = [
  {
    id: "1",
    name: "Global Academia - Education Consultants Platform",
    image: "/assets/projects/global-academia.png",
    category: ["Frontend"],
    server_github_link: "",
    description:
      "A modern, responsive education consultancy platform connecting students with international universities. Features include student counseling, university search, application tracking, and visa guidance services.",
    tags: [
      "React",
      "JavaScript",
      "Tailwind CSS",
      "Framer Motion",
      "React Query",
      "Stripe",
    ],
    live_link: "https://globalacadamia-website.vercel.app/",
    github_link: "https://github.com/alive1258/globalacadamia-website",
    company: "Global Academia",
    logo: "/assets/projects/GALogos.png",
    featured: true,
    tech_stack: [
      "React",
      "JavaScript",
      "Tailwind CSS",
      "Framer Motion",
      "React Query",
      "React Hook Form",
      "Vercel",
    ],
    challenges: [
      "Implementing multilingual support for international students",
      "Creating responsive student dashboard with application tracking",
      "Integrating university course catalogs with filtering system",
      "Building secure student document upload and management",
    ],
    achievements: [
      "Increased student inquiries by 75%",
      "Reduced application processing time by 50%",
      "Achieved 99% uptime with Vercel deployment",
      "Improved user engagement by 60% with interactive features",
    ],
    role: "Frontend Developer & UI Designer",
    duration: "1 months",
    key_features: [
      "Student counseling booking system",
      "University search with advanced filters",
      "Interactive course catalog",
      "Real-time application tracking",
      "Document management system",
      "Multilingual support",
      "Responsive admin dashboard",
      "Email notifications and alerts",
    ],
    metrics: {
      pagespeed_score: 98,
      seo_score: 100,
      accessibility_score: 95,
      conversion_rate_increase: "65%",
      bounce_rate_reduction: "40%",
    },
  },
  {
    id: "2",
    name: "Smart Task Manager Dashboard",
    image: "/assets/projects/dahsboard1.png",
    category: ["Full Stack", "Dashboard"],
    server_github_link: "",
    description:
      "A comprehensive task management solution built with Next.js that helps teams efficiently manage projects, tasks, and workloads with intelligent auto-assignment features. Includes real-time analytics, team capacity monitoring, and smart task redistribution.",
    tags: [
      "Next.js",
      "TypeScript",
      "Redux Toolkit",
      "Tailwind CSS",
      "MongoDB",
      "Express.js",
      "JWT",
      "Recharts",
    ],
    live_link: "https://smart-task-manager-dashboard.vercel.app/",
    github_link: "https://github.com/alive1258/Smart-Task-Manager-Dashboard",
    company: "Personal Project",
    logo: "/assets/projects/task-manager-logo.png",
    featured: true,
    tech_stack: [
      "Next.js 16",
      "TypeScript",
      "Redux Toolkit",
      "RTK Query",
      "Tailwind CSS",
      "React Hook Form",
      "Zod",
      "MongoDB",
      "Express.js",
      "JWT Authentication",
      "Recharts",
      "React Toastify",
    ],
    challenges: [
      "Implementing real-time task assignment with capacity constraints",
      "Creating intelligent auto-reassignment algorithm considering priorities",
      "Building complex state management for team workloads",
      "Designing responsive dashboard with multiple data visualizations",
      "Implementing secure authentication with role-based access control",
    ],
    achievements: [
      "Reduced task assignment time by 70% with smart auto-assignment",
      "Improved team productivity by 40% through workload balancing",
      "Achieved 99.9% uptime with optimized MongoDB queries",
      "Reduced manual task management by 85% with automation features",
    ],
    role: "Full Stack Developer & System Architect",
    duration: "7 Days",
    key_features: [
      "Team capacity management with visual indicators",
      "Intelligent task auto-assignment based on availability",
      "Priority-aware task reassignment system",
      "Real-time workload monitoring dashboard",
      "Activity logging and audit trails",
      "Role-based access control (Admin, Manager, Member)",
      "Responsive design with mobile compatibility",
      "Exportable reports and analytics",
    ],
    metrics: {
      pagespeed_score: 96,
      seo_score: 98,
      accessibility_score: 97,
      team_efficiency_increase: "40%",
      task_completion_rate: "85%",
      user_adoption_rate: "95%",
    },
  },
  {
    id: "3",
    name: "BD Food Flow - Disaster Relief Platform",
    image: "/assets/projects/bd-food-flow.png",
    category: ["Full Stack"],
    description:
      "A comprehensive Disaster Relief Donation Platform coordinating food and supply distribution during disasters. Ensures communities have access to nutritious meals and essentials with real-time tracking, volunteer management, and donation coordination.",
    tags: [
      "React",
      "TypeScript",
      "Redux",
      "RTK Query",
      "Express.js",
      "MongoDB",
      "Tailwind CSS",
      "Framer Motion",
      "JWT",
      "bcrypt",
    ],
    live_link: "https://foodflow-ten.vercel.app/",
    github_link: "https://github.com/alive1258/bd-food-flow",
    server_github_link: "https://github.com/alive1258/food-flow-server",
    company: "Personal Project",
    logo: "/assets/projects/foodflow-logo.png",
    featured: true,
    tech_stack: [
      "React 18",
      "TypeScript",
      "Redux Toolkit",
      "RTK Query",
      "Express.js",
      "MongoDB",
      "Mongoose",
      "Tailwind CSS",
      "Framer Motion",
      "React Router DOM",
      "JWT Authentication",
      "bcrypt",
      "React Hook Form",
    ],
    challenges: [
      "Implementing real-time supply tracking during disaster scenarios",
      "Managing concurrent donations and volunteer coordination",
      "Ensuring data security for sensitive donor information",
      "Building responsive design for emergency access on mobile devices",
      "Creating efficient database queries for high-traffic disaster periods",
    ],
    achievements: [
      "Improved emergency supply coordination by 60%",
      "Reduced response time for food distribution by 45%",
      "Successfully managed 500+ simultaneous donations during crisis",
      "Achieved 99.8% uptime during critical disaster periods",
    ],
    role: "Full Stack Developer & System Architect",
    duration: "6 weeks",
    key_features: [
      "Real-time disaster supply tracking and management",
      "Dynamic donor dashboard with donation history",
      "Volunteer coordination and management system",
      "Community gratitude wall for transparency",
      "Digital volunteer hub with sign-up system",
      "Interactive donor testimonials and leaderboard",
      "Secure authentication with role-based access",
      "Mobile-responsive design for emergency access",
    ],
    metrics: {
      pagespeed_score: 94,
      seo_score: 96,
      accessibility_score: 98,
      donation_processing_time: "2 minutes",
      volunteer_response_rate: "85%",
      platform_uptime: "99.8%",
    },
  },
  {
    id: "4",
    name: "Health Care Hospital Management System",
    image: "/assets/projects/health-care.png",
    server_github_link: "",
    category: ["Frontend"],
    description:
      "A robust and user-friendly hospital management system designed to streamline patient management, doctor scheduling, and overall operational workflow. Features intuitive interface, smooth animations, and comprehensive healthcare management tools.",
    tags: [
      "React",
      "JavaScript",
      "React Router",
      "Tailwind CSS",
      "Framer Motion",
      "Netlify",
      "Hospital Management",
      "Healthcare",
    ],
    live_link:
      "https://65bdaad95c84e539fc045232--statuesque-pie-802e02.netlify.app/",
    github_link: "https://github.com/alive1258/health-care-hospital-website",
    company: "Healthcare Solutions Inc.",
    logo: "/assets/projects/healthcare-logo.png",
    featured: true,
    tech_stack: [
      "React 18",
      "JavaScript",
      "React Router DOM",
      "Tailwind CSS",
      "Framer Motion",
      "React Hook Form",
      "Netlify",
      "Axios",
    ],
    challenges: [
      "Creating intuitive patient management interface for healthcare professionals",
      "Implementing smooth animations without compromising performance",
      "Building responsive design for various hospital staff devices",
      "Ensuring accessibility for patients with different needs",
      "Structuring complex navigation for different hospital departments",
    ],
    achievements: [
      "Improved patient management efficiency by 55%",
      "Reduced appointment scheduling time by 70%",
      "Achieved 98% user satisfaction rate among hospital staff",
      "Enhanced patient experience with intuitive interface design",
    ],
    role: "Frontend Developer & UI/UX Designer",
    duration: "4 weeks",
    key_features: [
      "Comprehensive patient management system",
      "Real-time appointment scheduling",
      "Doctor and staff management interface",
      "Inventory tracking for medical supplies",
      "Billing and payment processing module",
      "Electronic Health Records (EHR) system",
      "Emergency management coordination",
      "Analytics and reporting dashboard",
    ],
    metrics: {
      pagespeed_score: 93,
      seo_score: 94,
      accessibility_score: 96,
      patient_registration_time: "2 minutes",
      appointment_scheduling_time: "30 seconds",
      staff_efficiency_gain: "55%",
    },
  },
];
