export interface Project {
  id: string;
  name: string;
  image: string;
  category: string;
  description: string;
  tags: string[];
  live_link: string;
  github_link: string;
  company: string;
  logo: string;
  featured: boolean;
  tech_stack: string[];
  challenges: string[];
  achievements: string[];
  role: string;
  duration: string;
}

export const projectCategories = [
  "All",
  "Full Stack",
  "Frontend",
  "Backend",
  "E-commerce",
  "Dashboard",
  "Mobile",
  "AI/ML",
  "Web Application",
  "API Development",
];

export const projectsData: Project[] = [
  {
    id: "1",
    name: "Nexus Dashboard Pro - Enterprise Analytics Platform",
    image: "/images/projects/dashboard1.jpg",
    category: "Dashboard",
    description:
      "A comprehensive analytics dashboard with real-time data visualization, reporting capabilities, and interactive charts. Built with modern React patterns for optimal performance and user experience.",
    tags: [
      "Next.js 14",
      "TypeScript",
      "Tailwind CSS",
      "Recharts",
      "Prisma",
      "PostgreSQL",
    ],
    live_link: "https://nexus-dashboard.vercel.app",
    github_link: "https://github.com/username/nexus-dashboard",
    company: "Nexus Analytics",
    logo: "/images/projects/logo1.png",
    featured: true,
    tech_stack: [
      "Next.js 14",
      "TypeScript",
      "Tailwind CSS",
      "Shadcn UI",
      "Recharts",
      "Prisma",
      "PostgreSQL",
      "NextAuth",
    ],
    challenges: [
      "Real-time data synchronization",
      "Large dataset optimization",
      "Responsive design across all devices",
    ],
    achievements: [
      "95% performance score",
      "Reduced load time by 60%",
      "Scaled to 10K+ users",
    ],
    role: "Full Stack Developer",
    duration: "3 months",
  },
  {
    id: "2",
    name: "EcoShop - Modern E-commerce Platform",
    image: "/images/projects/ecommerce1.jpg",
    category: "E-commerce",
    description:
      "A full-featured e-commerce solution with secure payment processing, product management, and customer analytics. Integrated with Stripe and Sanity CMS for seamless operations.",
    tags: ["Next.js", "Stripe", "Sanity CMS", "MongoDB", "Redux", "Cloudinary"],
    live_link: "https://ecoshop-store.vercel.app",
    github_link: "https://github.com/username/ecoshop",
    company: "EcoShop Retail",
    logo: "/images/projects/logo2.png",
    featured: true,
    tech_stack: [
      "Next.js 14",
      "Stripe",
      "Sanity CMS",
      "Tailwind CSS",
      "Redux Toolkit",
      "MongoDB",
      "NextAuth",
      "Cloudinary",
    ],
    challenges: [
      "Payment gateway integration",
      "Inventory management",
      "Image optimization",
    ],
    achievements: [
      "Processed 1000+ orders",
      "99.9% uptime",
      "Mobile-first design",
    ],
    role: "Lead Developer",
    duration: "4 months",
  },
  {
    id: "3",
    name: "HealthTrack Pro - Health Monitoring App",
    image: "/images/projects/health1.jpg",
    category: "Mobile",
    description:
      "A health tracking application with real-time monitoring, AI-powered insights, and wearable device integration. Features activity tracking, nutrition logging, and health reports.",
    tags: ["React Native", "Node.js", "MongoDB", "Socket.io", "JWT", "Redis"],
    live_link: "https://healthtrack-app.vercel.app",
    github_link: "https://github.com/username/healthtrack",
    company: "HealthTech Solutions",
    logo: "/images/projects/logo3.png",
    featured: false,
    tech_stack: [
      "React Native",
      "Node.js",
      "Express.js",
      "MongoDB",
      "Socket.io",
      "JWT",
      "Redis",
      "Docker",
    ],
    challenges: [
      "Real-time sync across devices",
      "Battery optimization",
      "Data privacy compliance",
    ],
    achievements: ["50K+ downloads", "4.8-star rating", "HIPAA compliant"],
    role: "Mobile Developer",
    duration: "5 months",
  },
  {
    id: "4",
    name: "CodeCollab IDE - Real-time Code Editor",
    image: "/images/projects/code1.jpg",
    category: "Web Application",
    description:
      "A collaborative code editor with live coding sessions, chat functionality, and multiple language support. Built with operational transformation for conflict-free collaboration.",
    tags: ["React", "Node.js", "WebSockets", "Monaco Editor", "Docker", "AWS"],
    live_link: "https://codecollab.vercel.app",
    github_link: "https://github.com/username/codecollab",
    company: "DevCollab",
    logo: "/images/projects/logo4.png",
    featured: true,
    tech_stack: [
      "React",
      "Node.js",
      "WebSockets",
      "Monaco Editor",
      "Redis",
      "Docker",
      "AWS EC2",
      "NGINX",
    ],
    challenges: [
      "Real-time collaboration",
      "Multiple language support",
      "Scaling WebSocket connections",
    ],
    achievements: [
      "10K+ active users",
      "Real-time latency <100ms",
      "Open source community",
    ],
    role: "Full Stack Engineer",
    duration: "6 months",
  },
  {
    id: "5",
    name: "Artify AI - AI Art Generation Platform",
    image: "/images/projects/ai1.jpg",
    category: "AI/ML",
    description:
      "An AI-powered art generation platform with multiple models, style transfer, and community features. Generate images from text prompts and create artistic variations.",
    tags: [
      "Next.js",
      "Python",
      "OpenAI",
      "FastAPI",
      "Stable Diffusion",
      "Supabase",
    ],
    live_link: "https://artify-ai.vercel.app",
    github_link: "https://github.com/username/artify-ai",
    company: "Artify AI",
    logo: "/images/projects/logo5.png",
    featured: false,
    tech_stack: [
      "Next.js",
      "Python",
      "FastAPI",
      "OpenAI API",
      "Stable Diffusion",
      "Tailwind CSS",
      "Redis",
      "Supabase",
    ],
    challenges: [
      "API rate limiting",
      "Image generation speed",
      "Large file processing",
    ],
    achievements: [
      "Generated 50K+ images",
      "Active community",
      "Featured on Product Hunt",
    ],
    role: "AI Developer",
    duration: "3 months",
  },
  {
    id: "6",
    name: "TaskFlow Pro - Project Management Tool",
    image: "/images/projects/task1.jpg",
    category: "Web Application",
    description:
      "Advanced project management tool with kanban boards, timelines, resource management, and real-time collaboration. Features time tracking and comprehensive reporting.",
    tags: ["Vue.js 3", "NestJS", "PostgreSQL", "GraphQL", "Docker", "Redis"],
    live_link: "https://taskflow-app.vercel.app",
    github_link: "https://github.com/username/taskflow",
    company: "TaskFlow Inc.",
    logo: "/images/projects/logo6.png",
    featured: true,
    tech_stack: [
      "Vue.js 3",
      "NestJS",
      "PostgreSQL",
      "GraphQL",
      "Docker",
      "Jest",
      "Cypress",
      "Redis",
    ],
    challenges: [
      "Drag-and-drop interactions",
      "Real-time synchronization",
      "Large dataset performance",
    ],
    achievements: [
      "500+ teams onboarded",
      "95% user satisfaction",
      "Enterprise adoption",
    ],
    role: "Full Stack Developer",
    duration: "4 months",
  },
  {
    id: "7",
    name: "FinanceDash - Financial Analytics Dashboard",
    image: "/images/projects/finance1.jpg",
    category: "Dashboard",
    description:
      "A financial analytics platform with real-time stock data, portfolio tracking, and predictive analytics. Features advanced charting and investment insights.",
    tags: [
      "React",
      "TypeScript",
      "Chart.js",
      "Python",
      "FastAPI",
      "PostgreSQL",
    ],
    live_link: "https://financedash.vercel.app",
    github_link: "https://github.com/username/financedash",
    company: "FinanceDash Corp",
    logo: "/images/projects/logo7.png",
    featured: true,
    tech_stack: [
      "React",
      "TypeScript",
      "Chart.js",
      "Python",
      "FastAPI",
      "PostgreSQL",
      "Redis",
      "Docker",
    ],
    challenges: [
      "Real-time financial data",
      "Complex chart visualizations",
      "Data accuracy",
    ],
    achievements: [
      "99.5% data accuracy",
      "Real-time updates",
      "Bank-level security",
    ],
    role: "Backend Developer",
    duration: "5 months",
  },
  {
    id: "8",
    name: "LearnHub - Interactive Learning Platform",
    image: "/images/projects/learning1.jpg",
    category: "Web Application",
    description:
      "An interactive learning platform with video courses, quizzes, progress tracking, and community features. Supports multiple learning paths and certifications.",
    tags: ["Next.js", "MongoDB", "Stripe", "Cloudinary", "Socket.io", "Redis"],
    live_link: "https://learnhub.vercel.app",
    github_link: "https://github.com/username/learnhub",
    company: "LearnHub Education",
    logo: "/images/projects/logo8.png",
    featured: false,
    tech_stack: [
      "Next.js",
      "MongoDB",
      "Stripe",
      "Cloudinary",
      "Socket.io",
      "Redis",
      "NextAuth",
      "Tailwind",
    ],
    challenges: [
      "Video streaming optimization",
      "Progress tracking",
      "Payment integration",
    ],
    achievements: ["10K+ students", "95% completion rate", "Mobile responsive"],
    role: "Full Stack Developer",
    duration: "6 months",
  },
];
