import { baseApi } from "../api/baseApi";

// Define the shape of the response data for product-related endpoints
interface ProjectsResponse {
  _id: string;
  name: string;
  image: string;
  live_link: string;
  rating: number;
  review: number;
  category: string;
  gitHub_link: string;
  gitHub_link_server: string;
  video_showcasing: string;
  tec1: string;
  tec2: string;
  tec3: string;
  tec4: string;
  tec5: string;
  tec6: string;
  tec7: string;
  tec8: string;
  Des1: string;
  Des2: string;
  Des3: string;
  Des4: string;
  acknowledged: boolean;
}

// Define product-related API endpoints using `baseApi.injectEndpoints`
export const projectsApi = baseApi.injectEndpoints({
  endpoints: (builder) => ({
    // Define a query to fetch all products
    getProjects: builder.query<ProjectsResponse[], string>({
      query: () => ({
        url: "/projects",
        method: "GET",
      }),
      providesTags: ["projects"], // Cache tag for this endpoint
    }),

    // Define a query to fetch a single projects by ID
    getSingleProjects: builder.query<ProjectsResponse, string>({
      query: (id) => ({
        url: `/projects/${id}`,
        method: "GET",
      }),
    }),

    // Define a mutation to create a new projects
    createProjects: builder.mutation<
      ProjectsResponse,
      Partial<ProjectsResponse>
    >({
      query: (body) => ({
        url: "/projects",
        method: "POST",
        body,
      }),
      invalidatesTags: ["projects"], // Invalidate product cache after creating a new projects
    }),

    // Define a mutation to update an existing projects
    updateProjects: builder.mutation<
      ProjectsResponse,
      { id: string; body: Partial<ProjectsResponse> }
    >({
      query: ({ id, body }) => ({
        url: `/projects/${id}`,
        method: "PUT",
        body,
      }),
      invalidatesTags: ["projects"],
    }),

    // Define a mutation to delete a projects by ID
    deleteProjects: builder.mutation<ProjectsResponse, string>({
      query: (id) => ({
        url: `/projects/${id}`,
        method: "DELETE",
      }),
      invalidatesTags: ["projects"],
    }),
  }),
});

// Destructure hooks generated by the `productApi` for easy use
export const {
  useGetProjectsQuery,
  useCreateProjectsMutation,
  useDeleteProjectsMutation,
  useUpdateProjectsMutation,
  useGetSingleProjectsQuery,
} = projectsApi;
