import { baseApi } from "../api/baseApi";

// Define the shape of the response data for skillsApi endpoints
interface SkillsResponse {
  _id: string;
  name: string;
  image: string;
  acknowledged: boolean;
}

// Define skills-related API endpoints using `baseApi.injectEndpoints`
export const skillsApi = baseApi.injectEndpoints({
  endpoints: (builder) => ({
    // Define a query to fetch all experiences
    getSkills: builder.query<SkillsResponse[], string>({
      query: () => ({
        url: "/skills",
        method: "GET",
      }),
      providesTags: ["skills"], // Cache tag for this endpoint
    }),

    // Define a query to fetch a single skills by ID
    getSingleSkills: builder.query<SkillsResponse, string>({
      query: (id) => ({
        url: `/skills/${id}`,
        method: "GET",
      }),
    }),

    // Define a mutation to create a new skills
    createSkills: builder.mutation<SkillsResponse, Partial<SkillsResponse>>({
      query: (body) => ({
        url: "/skills",
        method: "POST",
        body,
      }),
      invalidatesTags: ["skills"], // Invalidate product cache after creating a new skills
    }),

    // Define a mutation to update an existing skills
    updateSkills: builder.mutation<
      SkillsResponse,
      { id: string; body: Partial<SkillsResponse> }
    >({
      query: ({ id, body }) => ({
        url: `/skills/${id}`,
        method: "PUT",
        body,
      }),
      invalidatesTags: ["skills"],
    }),

    // Define a mutation to delete a skills by ID
    deleteSkills: builder.mutation<SkillsResponse, string>({
      query: (id) => ({
        url: `/skills/${id}`,
        method: "DELETE",
      }),
      invalidatesTags: ["skills"],
    }),
  }),
});

// Destructure hooks generated by the `Skillsapi` for easy use
export const {
  useGetSkillsQuery,
  useCreateSkillsMutation,
  useDeleteSkillsMutation,
  useUpdateSkillsMutation,
  useGetSingleSkillsQuery,
} = skillsApi;
